### PR TITLE
LPS-157005 Assert the required error presence by the field label

### PR DESCRIPTION
**Pull request by miltonmc**
Related: https://issues.liferay.com/browse/LPS-157005

### CODE REVIEW

**Comment by miltonmc** [comment]
ci:test:sf

**Comment by miltonmc** [comment]
CC: @diogocordeiro

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by diogocordeiro** [comment]
Hi @evanilson-santana and @andreefarias @miltonmc did some refactoring on Macros of the Required field error message could you guys please take a look to see if anything is catching your attention.

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:objects

**Comment by miltonmc** [comment]
ci:test:object

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:forward

**Pull request closed without merging**
